// ──────────────────────────────────────────────────────────────────────────────
// apps/site/src/copy/landing.copy.ts
//
// Centralized copy deck for the REQNX landing page.
// All copy is typed. No marketing buzzwords (blazing, seamless, effortless, etc.),
// no exclamation points, no emojis.
// ──────────────────────────────────────────────────────────────────────────────

export interface HeadlineOption {
  id: string;
  headline: string;
  subhead: string;
  isPrimary?: boolean;
}

export const copyDeck = {
  hero: {
    eyebrow: 'Open source · MIT · Pre-release v0.x',
    headlineOptions: [
      {
        id: 'reason-about',
        headline: 'Rate limiting you can reason about.',
        subhead:
          'Pure state-transition functions running against your choice of storage. Five classical algorithms, zero runtime dependencies, and deterministic tests that control time.',
        isPrimary: true,
      },
      {
        id: 'know-why',
        headline: 'Limit requests. Know exactly why.',
        subhead:
          'Pluggable rate limiting for Node.js. Every decision includes limit, quota remaining, reset timestamp, and retry-after delay. No hidden state.',
        isPrimary: false,
      },
      {
        id: 'shows-work',
        headline: 'A rate limiter that shows its work.',
        subhead:
          'Written as verifiable mathematical state machines. Run the real library in your browser before adding it to your codebase.',
        isPrimary: false,
      },
      {
        id: 'plain-answer',
        headline: 'Pick an algorithm. Get a plain answer.',
        subhead:
          'Five algorithms from fixed windows to leaky buckets. Same decision interface, same atomicity guarantees, in memory or over Redis.',
        isPrimary: false,
      },
      {
        id: 'deterministic',
        headline: 'Deterministic rate limiting for distributed Node.js.',
        subhead:
          'Epoch-aligned windows and monotonic clocks prevent early quota resets. Zero runtime dependencies in core.',
        isPrimary: false,
      },
    ] as readonly HeadlineOption[],
    ctaPrimary: 'Get started',
    ctaSecondary: 'Try the playground',
    fromSourceLabel: 'Run it from source',
    installLabel: 'Install package',
    simulatedCaption:
      'Simulated time. This is the real @reqnx/core library running in your browser.',
    // Convenience accessors for primary headline and CTAs
    headline: 'Rate limiting you can reason about.',
    subhead:
      'Pure state-transition functions running against your choice of storage. Five classical algorithms, zero runtime dependencies, and deterministic tests that control time.',
    primaryCta: 'Get started',
    secondaryCta: 'Try the playground',
  },

  proofStrip: {
    title: 'Verified project facts',
    howComputedTitle: 'How these numbers are computed',
    howComputedLede:
      'Every statistic in this strip is extracted directly from the repository source code and build artifacts at site build time.',
  },

  boundaryStory: {
    eyebrow: 'Algorithm mechanics',
    title: 'Fixed windows have a seam',
    lede: 'Rigid window boundaries allow a burst centered at the seam to admit twice the limit across a brief interval. Here is the exact sequence recorded by the engine.',
    step1Caption:
      'Window 1 end: 5 requests arrive between 9,960 ms and 9,999 ms. All 5 are admitted.',
    step2Caption:
      'Window 2 start: 5 more requests arrive between 10,000 ms and 10,040 ms. A fresh window starts, and all 5 are admitted.',
    step3Caption:
      'The result: 10 requests admitted in an 80 ms span across the boundary, which is 2x the configured limit of 5.',
    conclusionAvailable:
      'This behavior is mathematically intrinsic to fixed windows. To eliminate boundary bursts, use Sliding Window Counter or Token Bucket when available.',
    conclusionPlanned:
      'Sliding Window Counter and Token Bucket algorithms are currently in development to provide smooth boundary transitions.',
  },

  algorithms: {
    eyebrow: 'Algorithms',
    title: 'Five classical strategies',
    lede: 'Choose the right trade-off between throughput, memory footprint, and burst tolerance. Each algorithm implements the same pure step interface.',
    matrixTitle: 'Trade-off comparison matrix',
    matrixNote:
      'Conceptual properties. Empirical throughput and memory measurements will be updated as benchmarks run.',
  },

  code: {
    eyebrow: 'Quickstart',
    title: 'Clean contracts. Plain decisions.',
    lede: 'Create a store, select an algorithm, and evaluate requests. The output on the right is generated by executing this exact snippet during the build.',
    callout1: '1. Select storage backend (in-memory or Redis)',
    callout2: '2. Configure algorithm parameters',
    callout3: '3. Check request cost against identity key',
    callout4: '4. Consume structured decision metadata',
  },

  guarantees: {
    eyebrow: 'Engineering guarantees',
    title: 'Correct by construction',
    lede: 'Rate limiting protects critical infrastructure. REQNX enforces strict mathematical and architectural constraints verified by automated tests.',
  },

  architecture: {
    eyebrow: 'Architecture',
    title: 'Data flow and separation of concerns',
    lede: 'The limiter validates input and applies failure policy; the store guarantees atomic execution; the algorithm is a pure state machine that never touches I/O or the system clock.',
    worksWithTitle: 'Compatibility matrix',
  },

  status: {
    eyebrow: 'Implementation progress',
    title: 'What works today',
    lede: 'Every available capability links directly to its source code, contract suite, or benchmark file in the repository.',
    availableLabel: 'Available',
    inProgressLabel: 'In progress',
    plannedLabel: 'Planned',
  },

  faq: {
    eyebrow: 'Frequently asked questions',
    title: 'Questions and technical answers',
    lede: 'Detailed explanations regarding production readiness, distributed deployment, and algorithmic behavior.',
    items: [
      {
        question: 'Is REQNX ready for production?',
        answer:
          'Fixed Window Counter with MemoryStore is implemented, fully tested, and benchmarked. RedisStore, framework adapters, and distributed Lua scripts are scheduled for Days 6 and 7. The core library is in pre-release v0.x.',
      },
      {
        question: 'Do I need Redis to use REQNX?',
        answer:
          'No. For single-process applications, background workers, or edge functions, MemoryStore provides synchronous, zero-dependency in-memory rate limiting with LRU eviction and memory bounds.',
      },
      {
        question: 'Which algorithm should I choose?',
        answer:
          'Use Fixed Window for highest throughput (>12M pure ops/s) when momentary boundary bursts are acceptable. Use Token Bucket for natural API bursts, or Sliding Window Counter to smooth traffic evenly.',
      },
      {
        question: 'Does REQNX run in browsers and edge runtimes?',
        answer:
          '@reqnx/core has zero runtime dependencies and makes no Node-specific syscalls. It runs in Node.js, Bun, Deno, Cloudflare Workers, and in modern web browsers.',
      },
      {
        question: 'How does REQNX handle backwards clock drift (NTP)?',
        answer:
          'Per ADR-0002 and ADR-0010, the algorithm locks onto stored window timestamps and never grants early quota renewal if the system clock steps backwards.',
      },
      {
        question: 'What happens when the storage backend fails?',
        answer:
          'The limiter facade implements configurable failure policies: fail-open (default, returns degraded: true), fail-closed, or a custom recovery function. Store failures never crash the process unhandled.',
      },
      {
        question: 'How do I contribute or add an algorithm?',
        answer:
          'Algorithms implement the pure Algorithm contract: step, peek, parseConfig, and stateTtlMs. Conformance is verified automatically by the testkit contract suite.',
      },
    ],
  },

  ctaBand: {
    title: 'Try it before you install it',
    lede: 'Run the interactive playground in your browser, explore the algorithm specifications, or inspect the source code on GitHub.',
    primary: 'Read the quickstart',
    secondary: 'Open the playground',
    github: 'View repository on GitHub',
  },

  footer: {
    trademarkNotice:
      'Redis is a registered trademark of Redis Ltd. Express and Fastify are trademarks of their respective owners. REQNX has no official affiliation with these projects.',
    trackingNotice: 'No cookies. No telemetry. No third-party trackers.',
  },
} as const;

export const landingCopy = copyDeck;
